### ISSUE TITLE
Locally installed eslint node module overrides the "eslint.nodePath" workspace setting.

### ISSUE THREAD

**Issue by lrs** [Microsoft/vscode-eslint#156]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Pro Version 1607 64bit
- Extensions Installed: 
  - Align v0.2.0
  - C# for Visual Studio Code (powered by OmniSharp) v1.4.1
  - EditorConfig for Visual Studio Code v0.3.3
  - Legacy OmniSharp Support for Visual Studio Code v0.3.3
  - React Native Tools v0.2.0
  - Unity Debugger Extension for Visual Studio Code v1.0.4
  - Unity Tools for Visual Studio Code v0.1.7
  - VS Code ESLint extension v1.0.8
  - VS Code - Debugger for Chrome v1.2.1
  - VS Code Unity Snippets v0.1.2
  - vscode-svgviewer v1.2.0
### Description

If you have a locally installed version of the eslint node module in a workspace, it will always be used instead of the path you specify in the **eslint.nodepath** workspace setting.

The eslint version that is set in the workspace settings should always be used.
### Steps to reproduce
- Make sure you have the latest version of the eslint node module globally installed.
  - Uninstall all globally installed versions of the eslint node module: `npm uninstall -g eslint`.
  - Install the latest version of eslint globally: `npm install -g eslint`.
- Create a new directory and initialise (npm init).
- Install an old version of eslint locally: `npm install --save-dev eslint@1.10.3`.
- Open in VSCode and set the **eslint.nodePath** in File>Preferences>Workspace Settings:
  - `{ "eslint.nodePath": "drive:\\path\\to\\global\\npm\\node_modules\\eslint" }`.
- Create a test JavaScript file and save a piece of code.
- Initialise a Git repository.
- Save a change to the test file, go to View>Git and click on the test file to view the diff.
- eslint will use the locally installed old version and throw an error: **Path must be a string. Received null**.
- This error wouldn't occur if the latest version of eslint that is set in your workspace settings is used.
### ESLint verbose trace from window reload

```
[Trace - 10:17:20] Sending request 'initialize - (0)'.
Params: {
    "processId": 9036,
    "rootPath": "d:\\temp\\vscode-eslint",
    "capabilities": {},
    "initializationOptions": {
        "legacyModuleResolve": false,
        "nodePath": "C:\\Users\\[user]\\AppData\\Roaming\\npm\\node_modules\\eslint"
    },
    "trace": "verbose"
}


[Trace - 10:17:22] 'npm config get prefix' value is: C:\Users\[user]\AppData\Roaming\npm
[Trace - 10:17:22] NODE_PATH value is: C:\Users\[user]\AppData\Roaming\npm\node_modules\eslint;C:\Users\[user]\AppData\Roaming\npm\node_modules
[Trace - 10:17:22] Received response 'initialize - (0)' in 2554ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "codeActionProvider": true
    }
}


[Info  - 10:17:22] ESLint server is running.
[Trace - 10:17:22] Sending notification '$/setTraceNotification'.
Params: {
    "value": "verbose"
}


[Trace - 10:17:22] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "eslint": {
            "enable": true,
            "nodePath": "C:\\Users\\[user]\\AppData\\Roaming\\npm\\node_modules\\eslint",
            "_legacyModuleResolve": false,
            "options": {},
            "trace": {
                "server": "verbose"
            },
            "run": "onType",
            "autoFixOnSave": false
        }
    }
}


[Trace - 10:17:22] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/temp/vscode-eslint/test.js",
        "languageId": "javascript",
        "version": 1,
        "text": "const tt = 42;\r\ntt = 43;\r\n"
    }
}


[Trace - 10:17:22] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "inmemory://model/3",
        "languageId": "javascript",
        "version": 1,
        "text": "const tt = 42;\r\ntt = 41;\r\n"
    }
}


[Trace - 10:17:22] Received notification 'eslint/noConfig'.
Params: {
    "state": 1
}


[Trace - 10:17:23] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///d%3A/temp/vscode-eslint/test.js",
    "diagnostics": [
        {
            "message": "Parsing error: Unexpected token const",
            "severity": 1,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 1
                }
            }
        }
    ]
}


[Trace - 10:17:23] Received notification 'eslint/noConfig'.
Params: {
    "state": 1
}


[Trace - 10:17:23] Received notification 'eslint/noConfig'.
Params: {
    "state": 3
}



```

**Comment by dbaeumer** [comment]
Fixed in upcoming 1.1.0.

**Comment by lrs** [comment]
Unfortunately, I'm still seeing the error with version 1.1.0. I tried re installing the ESLint extension with no effect.

Maybe I'm using the wrong syntax for the nodePath setting?

Here's the ESLint trace: 
```
[Trace - 13:56:26] Sending request 'initialize - (0)'.
Params: {
    "processId": 6860,
    "rootPath": "d:\\temp\\vscode-eslint",
    "capabilities": {},
    "initializationOptions": {
        "legacyModuleResolve": false,
        "nodePath": "C:\\Users\\[user]\\AppData\\Roaming\\npm\\node_modules"
    },
    "trace": "verbose"
}


[Trace - 13:56:29] Received response 'initialize - (0)' in 2239ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "codeActionProvider": true
    }
}


[Info  - 13:56:29] ESLint server is running.
[Trace - 13:56:29] Sending notification '$/setTraceNotification'.
Params: {
    "value": "verbose"
}


[Trace - 13:56:29] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "eslint": {
            "enable": true,
            "nodePath": "C:\\Users\\[user]\\AppData\\Roaming\\npm\\node_modules",
            "_legacyModuleResolve": false,
            "options": {},
            "trace": {
                "server": "verbose"
            },
            "run": "onType",
            "autoFixOnSave": false
        }
    }
}


[Trace - 13:56:29] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/temp/vscode-eslint/test.js",
        "languageId": "javascript",
        "version": 1,
        "text": "const tt = 42;\r\ntt = 43;\r\n"
    }
}


[Trace - 13:56:29] Received notification 'eslint/status'.
Params: {
    "state": 1
}


[Trace - 13:56:29] NODE_PATH value is: C:\Users\[user]\AppData\Roaming\npm\node_modules
[Trace - 13:56:33] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "ESLint library loaded from: C:\\Users\\[user]\\AppData\\Roaming\\npm\\node_modules\\eslint\\lib\\api.js"
}


[Info  - 13:56:33] ESLint library loaded from: C:\Users\[user]\AppData\Roaming\npm\node_modules\eslint\lib\api.js
[Trace - 13:56:34] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///d%3A/temp/vscode-eslint/test.js",
    "diagnostics": [
        {
            "message": "'tt' is assigned a value but never used. (no-unused-vars)",
            "severity": 2,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 0,
                    "character": 6
                },
                "end": {
                    "line": 0,
                    "character": 6
                }
            },
            "code": "no-unused-vars"
        },
        {
            "message": "'tt' is constant. (no-const-assign)",
            "severity": 2,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 1,
                    "character": 0
                },
                "end": {
                    "line": 1,
                    "character": 0
                }
            },
            "code": "no-const-assign"
        }
    ]
}


[Trace - 13:56:34] Received notification 'eslint/status'.
Params: {
    "state": 1
}


[Trace - 13:56:42] Sending notification 'textDocument/didClose'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/temp/vscode-eslint/test.js"
    }
}


[Trace - 13:56:42] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///d%3A/temp/vscode-eslint/test.js",
    "diagnostics": []
}


[Trace - 13:56:45] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/temp/vscode-eslint/test.js",
        "languageId": "javascript",
        "version": 1,
        "text": "const tt = 42;\r\ntt = 43;\r\n"
    }
}


[Trace - 13:56:45] NODE_PATH value is: C:\Users\[user]\AppData\Roaming\npm\node_modules
[Trace - 13:56:45] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "inmemory://model/5",
        "languageId": "javascript",
        "version": 1,
        "text": "const tt = 42;\r\ntt = 44;\r\n"
    }
}


[Trace - 13:56:45] NODE_PATH value is: C:\Users\[user]\AppData\Roaming\npm\node_modules
[Trace - 13:56:45] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "ESLint library loaded from: C:\\Users\\[user]\\AppData\\Roaming\\npm\\node_modules\\eslint\\lib\\api.js"
}


[Info  - 13:56:45] ESLint library loaded from: C:\Users\[user]\AppData\Roaming\npm\node_modules\eslint\lib\api.js
[Trace - 13:56:45] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///d%3A/temp/vscode-eslint/test.js",
    "diagnostics": [
        {
            "message": "'tt' is assigned a value but never used. (no-unused-vars)",
            "severity": 2,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 0,
                    "character": 6
                },
                "end": {
                    "line": 0,
                    "character": 6
                }
            },
            "code": "no-unused-vars"
        },
        {
            "message": "'tt' is constant. (no-const-assign)",
            "severity": 2,
            "source": "eslint",
            "range": {
                "start": {
                    "line": 1,
                    "character": 0
                },
                "end": {
                    "line": 1,
                    "character": 0
                }
            },
            "code": "no-const-assign"
        }
    ]
}


[Trace - 13:56:45] Received notification 'eslint/status'.
Params: {
    "state": 1
}


[Trace - 13:56:45] Sending request 'textDocument/codeAction - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/temp/vscode-eslint/test.js"
    },
    "range": {
        "start": {
            "line": 1,
            "character": 0
        },
        "end": {
            "line": 1,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 1,
                        "character": 0
                    },
                    "end": {
                        "line": 1,
                        "character": 0
                    }
                },
                "message": "'tt' is constant. (no-const-assign)",
                "severity": 2,
                "code": "no-const-assign",
                "source": "eslint"
            }
        ]
    }
}


[Trace - 13:56:45] Received response 'textDocument/codeAction - (1)' in 2ms.
Result: []


[Trace - 13:56:46] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "ESLint library loaded from: d:\\temp\\vscode-eslint\\node_modules\\eslint\\lib\\api.js"
}


[Info  - 13:56:46] ESLint library loaded from: d:\temp\vscode-eslint\node_modules\eslint\lib\api.js
[Trace - 13:56:46] Received notification 'eslint/status'.
Params: {
    "state": 3
}



```

**Comment by dbaeumer** [comment]
@Irs the nodePath value has to look something like this:

`{ "eslint.nodePath": "drive:\\path\\to\\global\\npm\\node_modules" }`

without the eslint in the path. The value is added to the NODE_PATH env variable interpreted by node when resolving modules. 

If this still doesn't work can you provide a little workspace I can clone from to reproduce the issue.

**Comment by lrs** [comment]
Looks like the nodePath is right.

I've added this repo as an example - [vscode-eslint-test](https://github.com/lrs/vscode-eslint-test)

Thanks.

**Comment by lrs** [comment]
FYI the package.json for my global eslint is:

```
{
  "_args": [
    [
      "eslint",
      ""
    ]
  ],
  "_from": "eslint@latest",
  "_id": "eslint@3.10.2",
  "_inCache": true,
  "_installable": true,
  "_location": "/eslint",
  "_nodeVersion": "4.4.7",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/eslint-3.10.2.tgz_1479252045464_0.18702688300982118"
  },
  "_npmUser": {
    "email": "nicholas+eslint@nczconsulting.com",
    "name": "eslint"
  },
  "_npmVersion": "2.15.8",
  "_phantomChildren": {},
  "_requested": {
    "name": "eslint",
    "raw": "eslint",
    "rawSpec": "",
    "scope": null,
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/eslint/-/eslint-3.10.2.tgz",
  "_shasum": "c9a10e8bf6e9d65651204778c503341f1eac3ce7",
  "_shrinkwrap": null,
  "_spec": "eslint",
  "_where": "",
  "author": {
    "email": "nicholas+npm@nczconsulting.com",
    "name": "Nicholas C. Zakas"
  },
  "bin": {
    "eslint": "./bin/eslint.js"
  },
  "bugs": {
    "url": "https://github.com/eslint/eslint/issues/"
  },
  "dependencies": {
    "babel-code-frame": "^6.16.0",
    "chalk": "^1.1.3",
    "concat-stream": "^1.4.6",
    "debug": "^2.1.1",
    "doctrine": "^1.2.2",
    "escope": "^3.6.0",
    "espree": "^3.3.1",
    "estraverse": "^4.2.0",
    "esutils": "^2.0.2",
    "file-entry-cache": "^2.0.0",
    "glob": "^7.0.3",
    "globals": "^9.2.0",
    "ignore": "^3.2.0",
    "imurmurhash": "^0.1.4",
    "inquirer": "^0.12.0",
    "is-my-json-valid": "^2.10.0",
    "is-resolvable": "^1.0.0",
    "js-yaml": "^3.5.1",
    "json-stable-stringify": "^1.0.0",
    "levn": "^0.3.0",
    "lodash": "^4.0.0",
    "mkdirp": "^0.5.0",
    "natural-compare": "^1.4.0",
    "optionator": "^0.8.2",
    "path-is-inside": "^1.0.1",
    "pluralize": "^1.2.1",
    "progress": "^1.1.8",
    "require-uncached": "^1.0.2",
    "shelljs": "^0.7.5",
    "strip-bom": "^3.0.0",
    "strip-json-comments": "~1.0.1",
    "table": "^3.7.8",
    "text-table": "~0.2.0",
    "user-home": "^2.0.0"
  },
  "description": "An AST-based pattern checker for JavaScript.",
  "devDependencies": {
    "babel-polyfill": "^6.9.1",
    "babel-preset-es2015": "^6.9.0",
    "babelify": "^7.3.0",
    "beefy": "^2.0.0",
    "brfs": "0.0.9",
    "browserify": "^12.0.1",
    "chai": "^3.5.0",
    "cheerio": "^0.19.0",
    "coveralls": "2.11.4",
    "dateformat": "^1.0.8",
    "ejs": "^2.3.3",
    "eslint-plugin-node": "^2.0.0",
    "eslint-release": "^0.10.0",
    "esprima": "^2.4.1",
    "esprima-fb": "^15001.1001.0-dev-harmony-fb",
    "gh-got": "^2.2.0",
    "istanbul": "^0.4.0",
    "jsdoc": "^3.3.0-beta1",
    "karma": "^0.13.22",
    "karma-babel-preprocessor": "^6.0.1",
    "karma-mocha": "^1.0.1",
    "karma-mocha-reporter": "^2.0.3",
    "karma-phantomjs-launcher": "^1.0.0",
    "leche": "^2.1.1",
    "linefix": "^0.1.1",
    "load-perf": "^0.2.0",
    "markdownlint": "^0.2.0",
    "mocha": "^2.4.5",
    "mock-fs": "^3.12.1",
    "npm-license": "^0.3.2",
    "phantomjs-prebuilt": "^2.1.7",
    "proxyquire": "^1.7.10",
    "semver": "^5.0.3",
    "shelljs-nodecli": "~0.1.0",
    "sinon": "^1.17.2",
    "temp": "^0.8.3",
    "through": "^2.3.6"
  },
  "directories": {},
  "dist": {
    "shasum": "c9a10e8bf6e9d65651204778c503341f1eac3ce7",
    "tarball": "https://registry.npmjs.org/eslint/-/eslint-3.10.2.tgz"
  },
  "engines": {
    "node": ">=4"
  },
  "files": [
    "LICENSE",
    "README.md",
    "bin",
    "conf",
    "lib",
    "messages"
  ],
  "gitHead": "0840068b845d5e449159afce00d178e357132810",
  "homepage": "http://eslint.org",
  "keywords": [
    "ast",
    "lint",
    "javascript",
    "ecmascript",
    "espree"
  ],
  "license": "MIT",
  "main": "./lib/api.js",
  "maintainers": [
    {
      "email": "nicholas+eslint@nczconsulting.com",
      "name": "eslint"
    },
    {
      "email": "ivolodin@gmail.com",
      "name": "ivolodin"
    },
    {
      "email": "nicholas@nczconsulting.com",
      "name": "nzakas"
    }
  ],
  "name": "eslint",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/eslint/eslint.git"
  },
  "scripts": {
    "alpharelease": "node Makefile.js prerelease -- alpha",
    "betarelease": "node Makefile.js prerelease -- beta",
    "browserify": "node Makefile.js browserify",
    "check-commit": "node Makefile.js checkGitCommit",
    "ci-release": "node Makefile.js ciRelease",
    "coveralls": "cat ./coverage/lcov.info | coveralls",
    "docs": "node Makefile.js docs",
    "gensite": "node Makefile.js gensite",
    "lint": "node Makefile.js lint",
    "perf": "node Makefile.js perf",
    "profile": "beefy tests/bench/bench.js --open -- -t brfs -t ./tests/bench/xform-rules.js -r espree",
    "release": "node Makefile.js release",
    "test": "node Makefile.js test"
  },
  "version": "3.10.2"
}
```

**Comment by dbaeumer** [comment]
@lrs I cloned your example. What I don't fully understand is why you set the nodePath value. The eslint extension does take global install eslint packages into consideration.

**Comment by dbaeumer** [comment]
OK. What I see is the following: if nodePath points to a unexisting directory the server fails with an exception

```
[Trace - 6:21:41 PM] NODE_PATH value is: C:\Users\dirkb\AppData\Roaming\nbm\v6.5.0\node_modules
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Error - 6:21:41 PM] Connection to server got closed. Server will not be restarted.
[Info  - 6:21:41 PM] ESLint server stopped.
```

Are you seeing the same ?

**Comment by lrs** [comment]
Yes. When I leave the dummy user in the nodePath ESLint falls over. So the nodePath is definitely being read. However, I think the point is that even though the global ESLint package is taken into consideration, you will still see the error in Git View that is caused by using the older local version.

I get the same error as you if the nodePath is incorrect ("C:\\Users\\[user]\\AppData\\Roaming\\npm\\node_modules"):
```
Error: spawn C:\Program Files (x86)\Microsoft VS Code\Code.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Error - 07:22:15] Connection to server got closed. Server will not be restarted.
[Info  - 07:22:15] ESLint server stopped.
```

So it appears that even though the up to date global package is being read, the older local package is still being used.

**Comment by lrs** [comment]
I should add that I'm ignoring node_modules in the test repo. So you would need to run npm install to get the local package. That might explain why you're questioning the need to set nodePath?

Thanks.

**Comment by dbaeumer** [comment]
OK. I fixed the problem of the exception and now your test workspace works fine (after doing an npm install). Until I publish a new version of the eslint extension I recommend to have eslint installed locally.

**Comment by lrs** [comment]
Thanks, my bad for not explaining in the README! Do you mean have ESLint installed globally and not rely on nodePath?

**Comment by lrs** [comment]
I mean all is fine using the global package without a local package installed and not setting the nodePath.

**Comment by dbaeumer** [comment]
You should only need to use eslint.nodePath if our eslint module lives in a non default location (local of global)

**Comment by lrs** [comment]
Or if somehow another instance is being recognized by vscode-eslint and I want to ensure what instance to use by setting the nodePath. 

With respect, this is the issue that you asked me raise here in the first place.

**Comment by dbaeumer** [comment]
Agree and if you want to override and the override should work now. Or did it still not work for you.

**Comment by lrs** [comment]
Have you pushed an update to the extension? I'm on 1.1.0. and there's no notification of an update for me.

**Comment by dbaeumer** [comment]
1.1.0 should behave correctly in terms of preferring nodePath over locally installed packages. However I have not delievered a new version yet for the fix in https://github.com/Microsoft/vscode-eslint/issues/156#issuecomment-261431451

**Comment by lrs** [comment]
In that case, I am not seeing that the extension is preferring the nodePath setting for 1.1.0. I am still seeing the exception "ErrorPath must be a string. Received null" in Git View when there is an older version of ESLint installed locally.

I think the server crashing for a non existing nodePath is a separate issue?

**Comment by lrs** [comment]
Snippet from the Eslint trace:
```
[Trace - 21:06:54] NODE_PATH value is: C:\Users\[user]\AppData\Roaming\npm\node_modules
...
[Info  - 21:07:01] ESLint library loaded from: d:\temp\vscode-eslint\node_modules\eslint\lib\api.js
```

**Comment by dbaeumer** [comment]
"ErrorPath must be a string. Received null" is a separate issue caused by older eslint version running on node 6.x. Node now throws if you call some of the path methods with undefined/null. Before they simply returned and empty string. You will experience the same behavior on the command line

From which location do you expect ESLint to be loaded in your example?

**Comment by lrs** [comment]
I was following on from the point you made [here](https://github.com/Microsoft/vscode/issues/13496#issuecomment-254294920).

So I thought it was agreed that EsLint should be using the location set in nodePath regardless of any other instances?

**Comment by dbaeumer** [comment]
It should prefer node modules from the nodePath over locally over globally installed once. If no module is found in nodePath but one locally or globally it still uses the local or global one. This is in line with the general NODE_PATH environment variable. 

Could you share a workspace on GitHub that shows the problem you are seeing. I think I don't really understand your problem.

**Comment by lrs** [comment]
I created a new workspace and uploaded it to a new repo [here](https://github.com/lrs/vscode-eslint-2) to double check any problems with the previous workspace I uploaded and hopefully be more descriptive.

It does appear that the nodePath in .vscode/settings.json is being ignored for some reason. I am happy to be corrected if I have configured anything wrong.

If this is by design then that's totally fine as I can't see the need to have an older version of eslint installed locally anyway.

I do kind of feel like I've been "dumped" with the task of bringing this up from the previous issue [#13496](https://github.com/Microsoft/vscode/issues/13496) so I'm not sure how much more information I can add.

**Comment by dbaeumer** [comment]
Thanks again for the test case. I was asking for it again since I couldn't repro it and interestingly enough I can't repro it using your new example on ESLint 1.1.0 :-(

Here is what I see after changing the nodePath to `"eslint.nodePath": "C:\\tmp\\node_modules"`. Is there anything special you could think of with your D: drive?

![capture](https://cloud.githubusercontent.com/assets/1931590/20664728/d0a73bf2-b55c-11e6-93b4-31477111fc9f.png)

**Comment by lrs** [comment]
The error only occurs when using the *Git View* and clicking on the js file. Can you screen shoot what you see when you go to Git View and click on index.js?

From the Explorer view I see the same as you:
![explorer_view](https://cloud.githubusercontent.com/assets/582574/20666298/7b41eac8-b55b-11e6-8ab0-dc227161cb01.jpg)

I just added the node_module path to D:\Temp to see if there would be any different behavior from the normal global path. I don't think there was.

**Comment by dbaeumer** [comment]
I can reproduce it. Need to investigate what causes this. Looking at the trace the error seems not to come from the eslint server.
