### ISSUE TITLE
Error `unable to resolve path to module. eslint import/no-unresolved` but only in VSCode, not in ESLint CLI

### ISSUE THREAD

**Issue by alexleboucher** [microsoft/vscode-eslint#1994]
I upgraded the package [eslint-import-resolver-typescript](https://github.com/import-js/eslint-import-resolver-typescript) from `3.7.0` to `4.2.1` and VSCode ESLint shows errors `unable to resolve path to module. eslint import/no-unresolved` on my imports.

<img width="784" alt="Image" src="https://github.com/user-attachments/assets/f5b947fc-9d8e-4b15-970c-ba7e6474a723" />

I created an issue on the `eslint-import-resolver-typescript` repo (https://github.com/import-js/eslint-import-resolver-typescript/issues/396) but as the error is related to VSCode and not ESLint CLI, the main contributor suggested me to create an issue on your repository.
The package uses a napi module: [rspack-resolver](https://github.com/unrs/rspack-resolver) under the hood.

You can easily reproduct the issue by cloning my project : [docker-express-postgres-boilerplate](https://github.com/alexleboucher/docker-express-postgres-boilerplate) and upgrading the library `eslint-import-resolver-typescript`

**Comment by dbaeumer** [comment]
I am not able to reproduce this

![image](https://github.com/user-attachments/assets/d4f984a9-c133-4a5e-84d1-18772b4a7134)

Any additional things I need to do?

**Comment by thewilkybarkid** [comment]
I'm seeing something similar. I'm also seeing:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/f4233347-3c24-4327-b73d-4211cfcd4399" />

(There's one of these for each of the `import/*` rules enabled.)

**Comment by hyorimitsu** [comment]
I'm also facing the same issue. It seems to be reproducible when upgrading `eslint-import-resolver-typescript` to version [3.9.0](https://github.com/import-js/eslint-import-resolver-typescript/releases/tag/v3.9.0) or later. For reference, I'm also using a macOS.

**Comment by alexleboucher** [comment]
> I am not able to reproduce this
> 
> ![image](https://github.com/user-attachments/assets/d4f984a9-c133-4a5e-84d1-18772b4a7134)
> 
> Any additional things I need to do?

Is someone in the repo team able to reproduce it now?

**Comment by renchap** [comment]
I am also facing this issue. It happens for the non-relative imports that use aliases defined in `tsconfig.json`, and only for the non-type imports somehow:

<img width="804" alt="Image" src="https://github.com/user-attachments/assets/863ee720-405d-4349-97dc-d24db2de434c" />

If I run `eslint` manually from this file in the terminal, it does work correctly.

I am using a monorepo, with `"eslint.workingDirectories": [{ "pattern": "./packages/*/" }]`.

Is there a way to get more information to understand what is different between `eslint` ran from the VSCode extension vs from the CLI?

**Comment by dbaeumer** [comment]
@renchap do you have a GitHub repository I can clone that demos this. May be I can reproduce it there. Without being able to reproduce the error it is very hard to say what is the root cause of this.

**Comment by Serhansolo** [comment]
Hi, I am also facing this issue!

You don't need a repo, just install vue with [create vue](https://vuejs.org/guide/scaling-up/tooling.html) (`npm create vue@latest`)

![Image](https://github.com/user-attachments/assets/4f7ca4dc-5907-49ab-9dc5-d1915ffdf9ef)

I have a fresh install of Vue with vue-create. I am therefore using the flat-config.

With these settings (w/o OxLint):

![Image](https://github.com/user-attachments/assets/0a98a947-c95a-455f-85ea-720db982bbc0)

For some reason, the default installation of Vue does not use '@'  alias.  Once I change the imports to use the alias I see the mentioned error.

Vue comes with a default `eslint.config.ts` file.  In my new project, I tried numerous setups. With the TS config file.  using the Vue helpers and also a config from scratch.. I noticed that sometimes, for pure random reasons, the IDE does resolve the paths ... but after a while, it stops working.

**Comment by dbaeumer** [comment]
I would really prefer a GitHub repository I can clone. This ensures that I do use the same exact content and settings as you do. This repository should also contain you local VS Code settings if you changed any.

**Comment by Serhansolo** [comment]
Okay, I cannot believe this. I just arrived at my workplace only to realize that the screenshots I took earlier were fixed by elves. I cannot reproduce it anymore.

**Comment by renchap** [comment]
I still do not have a repository reproducing this, but I managed to figure out how to fix it:

In my package's `eslint.config.mjs` if I add:

```
    settings: {
      "import/resolver": {
        typescript: {
          project: "<root>/packages/web/tsconfig.json",
        },
      },
    },
```

Then it works. My package is located in `packages/web` from the root of the git repository (and root of the VSCode project).

So it looks like the `cwd` is somehow incorrect when `eslint` is invoked from vscode, and/or `eslint-import-resolver-typescript` does not set it correctly?

**Comment by renchap** [comment]
And another update: it worked for a few minutes, I continued to try to figure out a working config without this hardcoded path, and now the `no-unresolved` errors are back in vscode.

Could it be a different behaviour depending on the current active file when the `eslint` server is started, or something similar?

**Comment by Serhansolo** [comment]
Yo @renchap, I have had the same problems after the overnight elves fixed my vscode, I returned to work over the weekend, and guess what, red scribbles everywhere....

Then, after some vigorous googling, I found this baby: https://www.npmjs.com/package/eslint-import-resolver-typescript


_**Important notice:** I am using ` import-x` instead of `import`, according to the docs, it's faster. The rules are pretty much the same, you have to change the package and rule prefix._


This is my entire config, take out of it what you need, but pay attention to the `import-x/resolver-next` bit, that does the magic. 


```ts
  // import plugin
  flatConfigs.recommended,
  flatConfigs.typescript,
  {
    rules: {
      "import-x/consistent-type-specifier-style": ["error", "prefer-top-level"],
      "import-x/first": "warn",
      "import-x/newline-after-import": ["error", { count: 1 }],
      "import-x/no-absolute-path": "error",
      "import-x/no-relative-packages": "error",
      "import-x/order": "off",
      "sort-imports": "off",
      "sort-keys": "off",
    },
    settings: {
      "import-x/resolver-next": [
        createTypeScriptImportResolver({
          project: "./tsconfig.app.json",
        }),
      ],
    },
  },
```

**Comment by iwan-uschka** [comment]
I faced the same issue after migrating from yarn to pnpm. According to https://stackoverflow.com/a/78709106/3042035 i added the packages to the `devDependencies` of the root `package.json` and voilá, VS Code is happy. I am sure, this is not a fix but hopefully a workaround for now.

**Comment by lucaslcode** [comment]
I encountered this and was able to fix it by uninstall the VSCode eslint plugin (both on remote and local, I am using WSL), restarting vscode, and reinstalling the plugin

**Comment by iwan-uschka** [comment]
> [@renchap](https://github.com/renchap) do you have a GitHub repository I can clone that demos this. May be I can reproduce it there. Without being able to reproduce the error it is very hard to say what is the root cause of this.

Hi @dbaeumer, can you have a look at https://github.com/iwan-uschka/vscode-eslint-issue-1994/tree/feature/with-flaky-error please? I added a README how to reproduce the odd behavior.

I have to say that i wasn't able to create a monorepo from scratch reproducing this error. I ended up forking my project, removing everything unnecessary and adding some more code for testing purposes. Admitting that i am not sure if this is really/only a bug in some plugin or a misconfiguration of ESLint and/or TS in this repo.

**Comment by dbaeumer** [comment]
@renchap in general ESLint is very sensitive to the working directory. So if you have a mono repository you need to let the extension know the working directory that should be used when validating files. This is best done using the `eslint.workingDirectories` setting.

**Comment by renchap** [comment]
I have this config:
```json
    "eslint.workingDirectories": [
      { "pattern": "./packages/*/" },
    ],
```

I also tried to list the packages directly, but it still sometimes stop working randomly

Right now the only way I found to not have those random breakages is to hardcode the path in the eslint import config:

```
    settings: {
      "import/resolver": {
        typescript: {
          project: "/Users/renchap/dev/project/packages/web/tsconfig.json",
        },
      },
    },
```

If I omit it, or use a relative directory, after some point eslint ran by the vscode plugin stops resolving the paths proprely.

**Comment by iwan-uschka** [comment]
Thank you @renchap!! After referencing TS config in ESLint config as like

```JS
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const tsConfigEsLintPath = path.resolve(__dirname, 'tsconfig.eslint.json');

const config = [
  ...
  {
    settings: {
      'import/resolver': {
        typescript: {
          project: tsConfigEsLintPath,
        },
      },
    },
  },
];

export default config;

```

(https://github.com/iwan-uschka/vscode-eslint-issue-1994/commit/36405e54a75cdfae0974b8758b8dc99f60dec880)

i couldn't reproduce the issue 🎉 So cool. Hopefully the problem is now fixed and not just less flaky.

---

@dbaeumer Before in my [demo monorepo](https://github.com/iwan-uschka/vscode-eslint-issue-1994/tree/feature/with-flaky-error) i gave

```JSON
"eslint.workingDirectories": [{ "pattern": "./{apps,packages}/*/" }]
```
 and

```JSON
"eslint.workingDirectories": ["./apps/storybook-ui", "./packages/ui", "./packages/ui2"]
```

a try without any luck.

**Comment by JounQin** [comment]
Seems same of https://github.com/import-js/eslint-import-resolver-typescript/issues/447#issuecomment-2857366498

Maybe `eslint.runtime： node`: https://github.com/microsoft/vscode-eslint#:~:text=is%20false.-,eslint.runtime,-%2D%20use%20this%20setting would help.

**Comment by dbaeumer** [comment]
@renchap do you have  repository I can clone that demos what you are seeing. I would like to understand why relative paths don't work for you.

**Comment by JounQin** [comment]
@dbaeumer Did you check https://github.com/import-js/eslint-import-resolver-typescript/issues/447#issuecomment-2857344827?

I think this issue could happen when installing VSCode as arm64 arch, but install `unrs-resolver` in terminal in `x86_64` although I don't know what's happening, maybe the Node execution is installed via Rosetta 2? cc @valleywood

**Comment by dbaeumer** [comment]
@JounQin thanks. This comment https://github.com/microsoft/vscode-eslint/issues/1994#issuecomment-2739863146 is definitely related to your link. @thewilkybarkid

**Comment by iwan-uschka** [comment]
Thanks @dbaeumer for looking into it!

Curious about https://github.com/microsoft/vscode-eslint/issues/1994#issuecomment-2859087484. I am running macOS on an Apple M1 (Silicon, arm64).

**Comment by JounQin** [comment]
@iwan-uschka Can you confirm:

1. What's installed under `node_modules/@unrs/resolver-binding-*`
2. What's your VSCode's binary arch?
3. What's your Node's binary arch?

**Comment by iwan-uschka** [comment]
@JounQin, here we go:
1. Does the info about an existing `node_modules/.pnpm/@unrs+resolver-binding-darwin-arm64@1.7.2/node_modules/@unrs/resolver-binding-darwin-arm64/package.json` help?
2. How to determine that?
3. How to determine that?
4. No

**Comment by JounQin** [comment]
@iwan-uschka Thanks.

1. Yes, it indicates `arm64` is resolved instead of `x86_64`
2. <img width="315" alt="Image" src="https://github.com/user-attachments/assets/bf1ede34-61e9-4653-ad5f-585147338dcd" />
3. `node -p "process.arch"`
4. OK, unfortunate

**Comment by iwan-uschka** [comment]
Missing bits:

2. VS Code:
```
Version: 1.99.3 (Universal)
Commit: 17baf841131aa23349f217ca7c570c76ee87b957
Date: 2025-04-15T23:18:46.076Z (3 wks ago)
Electron: 34.3.2
ElectronBuildId: 11161073
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.4.0
```
3. `arm64`

**Comment by auirarrazaval** [comment]
Hi! I was [ redirected here from the eslint-plugin-import-x issues ](https://github.com/un-ts/eslint-plugin-import-x/issues/370) in order to report this. I do have a small reproduction link to reproduce it. As my original issue said, the extension picks up imports correctly initially, but as soon as there's a 'workspace change' (i change into a file in a different package/app), then the path resolution breaks.

Here is my reproduction link:
https://github.com/auirarrazaval/import-x-bug-no-unresolved-bug

**Comment by dbaeumer** [comment]
@auirarrazaval thanks for the repro. Can you please add an extensions.json to the settings folder listing the Vue extensions you are using.

**Comment by auirarrazaval** [comment]
@dbaeumer Added 👌 . I added other extensions the could maybe affect in any way.

**Comment by dbaeumer** [comment]
Is it on purpose that the imports are different:

```
import ComponentA from '@/components/ComponentA.vue';
import ComponentB from './components/ComponentB.vue';
```

For ComponentA it is @ and not relative. If I make both the same then they are either both OK for both fail.

**Comment by auirarrazaval** [comment]
@dbaeumer yes it's on purpose, because it's the alias resolving that fails

**Comment by dbaeumer** [comment]
@JounQin I investigate @auirarrazaval repro and here is what is happening:

- since he uses working directories validating the files happens on different current working directories of the server (e.g. once `process.cwd()` is `packages\eslint` or `apps\app-1` depending on which file is validated
- the eslint server is a long running process. The directory changes are done by doing a `process.cwd` call
- I looked that implementation here https://github.com/un-ts/eslint-plugin-import-x and it looks like you cache some module resolution. 

Could it be that the caching is not expected the `process.cwd` to change? That would explain the different results depending on which files opens first.

**Comment by JounQin** [comment]
> Could it be that the caching is not expected the `process.cwd` to change? That would explain the different results depending on which files opens first.

@dbaeumer Oh, I didn't expect `process.cwd()` could change at the first place, isn't that immutable?

> I looked that implementation here [un-ts/eslint-plugin-import-x](https://github.com/un-ts/eslint-plugin-import-x) and it looks like you cache some module resolution.

Your link is pointing to the repository homepage, I'd expect a detail link instead?

**Comment by dbaeumer** [comment]
@JounQin you can change the working directory using `process.cwd('new path')`. The cache I had in mind was https://github.com/un-ts/eslint-plugin-import-x/blob/master/src/utils/module-cache.ts but please be aware that I only looked through the code today for ~20 minutes.

**Comment by JounQin** [comment]
Hi, all, would you like to give the following a try?

```sh
# npm
npm i -D https://pkg.pr.new/eslint-plugin-import-x@388

# yarn
yarn add -D eslint-plugin-import-x@https://pkg.pr.new/eslint-plugin-import-x@388
```

See also https://github.com/un-ts/eslint-plugin-import-x/pull/388

**Comment by dbaeumer** [comment]
I will close the issue since the fix will be provided by @JounQin in the ESLint plugin. Thank you @JounQin

**Comment by renchap** [comment]
I am not using `eslint-plugin-import-x` but `eslint-plugin-import`, and having this issue. Does it mean that `eslint-plugin-import` also needs a similar fix?

**Comment by iwan-uschka** [comment]
@renchap just curious, if https://github.com/microsoft/vscode-eslint/issues/1994#issuecomment-2854344665 helps you as well.

**Comment by dbaeumer** [comment]
Does anyone know if `eslint-plugin-import` uses some caching for module locations as well?

**Comment by JounQin** [comment]
@dbaeumer 

Here it is:

https://github.com/import-js/eslint-plugin-import/blob/01c9eb04331d2efa8d63f2d7f4bfec3bc44c94f3/src/exportMap/childContext.js#L49

**Comment by dbaeumer** [comment]
@JounQin do you have an issue in our repository I can refer to. The I will open an issue again `eslint-plugin-import`

**Comment by JounQin** [comment]
> [@JounQin](https://github.com/JounQin) do you have an issue in our repository I can refer to. The I will open an issue again `eslint-plugin-import`

@dbaeumer You mean something like #388?

**Comment by sukkuuuuu** [comment]
This might be relevant.

https://github.com/microsoft/vscode-eslint/issues/1992#issuecomment-3138233237

**Comment by NishargShah** [comment]
It is still not resolved, someone can check it, if possible?

Link: https://github.com/un-ts/eslint-plugin-import-x/issues/370#issuecomment-3282688344

**Comment by wendev542** [comment]
Had the same issue, I fixed it by bumping my Node version from 22 to 24 and reinstalling my dependencies. Hope this helps anyone else stuck on this.
